# Generated by Django 5.1.2 on 2024-11-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProfilePic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default-profile.png', upload_to='profile_pics/'),
        ),
    ]
